#!/bin/bash

APP_NAMESPACE=$(kubectl apply -f istio/envs/nobuild/namespace.yaml -o name | cut -d '/' -f 2)
if [ -z "$APP_NAMESPACE" ]; then
    echo unable to create namespace for env nobuild
    exit 1
fi

# create the scecret for database credentials
kustomize build . | kubectl apply  -n $APP_NAMESPACE -f -  

kustomize build dashboard/k8s/envs/nobuild        | kubectl apply -f -
kustomize build customer-v1/k8s/envs/nobuild      | kubectl apply -f -
kustomize build casa-account-v1/k8s/envs/nobuild  | kubectl apply -f -  
kustomize build casa-account-v2/k8s/envs/nobuild  | kubectl apply -f -  
kustomize build ext-cust-svc/k8s/envs/nobuild     | kubectl apply -f -

if [ "$1" == "--load" ]; then
    kustomize build load-generator/k8s/envs/nobuild | kubectl apply -f -
fi

kubectl config set-context --current --namespace $APP_NAMESPACE
kubectl get pods

# deploy istio configs
kustomize build istio/envs/nobuild     | kubectl apply -f -
