#!/bin/bash


EVANS=$(which evans)

if [ -z "$EVANS" ]; then
    echo "evans not found. please download from https://github.com/ktr0731/evans/releases"
    exit 1
fi

# exit when any command fails
set -e

source ../common.sh
get_ingress_addr

[ -z "$DEMOBANK_PORT" ] && exit 1

ACCOUNT_ID=$1
[ -z "$ACCOUNT_ID" ] && ACCOUNT_ID="10001000"

echo calling gRPC service at ${DEMOBANK_HOST}:${DEMOBANK_PORT} with account_id = ${ACCOUNT_ID}
echo { \"login_name\": \"${ACCOUNT_ID}\" } | $EVANS \
         --proto ../protos/demo_bank.proto   \
         --host $DEMOBANK_HOST \
         --port $DEMOBANK_PORT \
         cli \
         call \
         demobank.api.DashboardService.GetDashboard
