apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: casa-account
spec:
  hosts:
    - casa-account
  http:
    - route:
        - destination:
            host: casa-account
            subset: v1
          weight: 50
        - destination:
            host: casa-account
            subset: v2
          weight: 50

---
kind: DestinationRule
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: casa-account
spec:
  host: casa-account
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
    - labels:
        version: v1
      name: v1
    - labels:
        version: v2
      name: v2
