apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: customer
spec:
  hosts:
    - customer
  http:
    - route:
        - destination:
            host: customer
            subset: v1
          weight: 100

---
kind: DestinationRule
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: customer
spec:
  host: customer
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
    - labels:
        version: v1
      name: v1
