apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ext-cust-svc
spec:
  hosts:
    - ext-cust-svc
  http:
    - fault:
        delay:
          fixedDelay: 10ms
          percentage:
            value: 0
      route:
        - destination:
            host: ext-cust-svc            