resources:
- ../../base

namespace: breeze

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: casa-account-v1
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/0
        value: { "name": "TRACING_JAEGER_ENDPOINT", "value": "http://jaeger-collector.istio-system:14268/api/traces" }
      - op: add
        path: /spec/template/spec/containers/0/env/1
        value: { "name": "APP_LOG_LEVEL", "value": "info" }

# the environment variable name must match application.yml setting
# in order to override it
