resources:
  - ../../base

namespace: playground

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: customer-v1
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/0
        value: { "name": "TRACE_WITH_STACKDRIVER", "value": "true" }
