resources:
  - ../../base

namespace: breeze

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: casa-account-v2
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/0
      value: { "name": "JAEGER_AGENT_HOST", "value": "jaeger-agent.istio-system" }
    - op: add
      path: /spec/template/spec/containers/0/env/0
      value: { "name": "JAEGER_AGENT_PORT", "value": "6832" }
