resources:
- ../../base

namespace: playground

patchesJson6902:
  - target:
      group: networking.istio.io
      version: v1alpha3
      kind: Gateway
      name: bank-gateway
    patch: |-
      - op: replace
        path: /spec/servers/0/hosts/0
        value: "dashboard.red.vino9.net"
