apiVersion: skaffold/v2beta2
kind: Config
metadata:
  name: customer-v1

build:
  artifacts:
  - image: gcr.io/vino9-276317/demo-bank/customer-v1
    jib:
      args:
        - -DskipTests
        - -Pjib

deploy:
  kustomize:
    paths:
      - k8s/envs/local

profiles:
  - name: gke
    activation:
      - kubeContext: gke1
    build:
      googleCloudBuild:
        projectId: vino9-276317
    deploy:
      kustomize:
        paths:
          - k8s/envs/gke
