micronaut:
  application:
    name: casa-account-v1

grpc:
  server:
    keep-alive-time: 3h

tracing:
  jaeger-endpoint: off
  use-stackdriver: false

datasources:
  default:
    url: jdbc:mysql://192.168.39.1:3306/demo
    username: demo
    password: demo
    dialect: MYSQL

flyway:
  datasources:
    default:
      enabled: true
      baseline-on-migrate: true