apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
spec:
  selector:
    matchLabels:
      job: load-generator
  template:
    metadata:
      labels:
        job: load-generator
    spec:
      containers:
        - name: locust
          image: gcr.io/vino9-276317/demo-bank/load-generator
          env:
            - name: DASHBOARD_SVC_ADDR
              value: "dashboard:50051"
            - name: USERS
              value: "10"
            - name: BOOM_PARAMS
              value: "--max-rps 1000"
            - name: MYSQL_CONN_STRING
              valueFrom:
                secretKeyRef:
                  name: demo-secret
                  key: mysql-conn-string
