apiVersion: v1
kind: Service
metadata:
  name: load-generator
spec:
  ports:
    - port: 8089
      name: http
  type: ClusterIP
  selector:
    app: load-generator

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
spec:
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      containers:
        - name: locust
          image: gcr.io/vino9-276317/demo-bank/load-generator
          env:
            - name: SVC_ADDR
              value: "dashboard:50051"
            - name: USERS
              value: "1"
