apiVersion: apps/v1
kind: Deployment
metadata:
  name: casa-account-v1
  labels:
    app: casa-account
    version: v1
spec:
  selector:
    matchLabels:
      app: casa-account
      version: v1
  template:
    metadata:
      labels:
        app: casa-account
        version: v1
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          image: gcr.io/vino9-276317/demo-bank/casa-account-v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
              protocol: TCP
          env:
            - name: GRPC_LISTEN_ADDR
              value: ":50051"
          resources:
            requests:
              cpu: 250m
              memory: 192Mi
            limits:
              cpu: 1000m
              memory: 384Mi
---
apiVersion: v1
kind: Service
metadata:
  name: casa-account
spec:
  type: ClusterIP
  selector:
    app: casa-account
  ports:
    - name: grpc
      port: 50051
