apiVersion: apps/v1
kind: Deployment
metadata:
  name: casa-account-v1
  labels:
    app: casa-account
    version: v1
spec:
  selector:
    matchLabels:
      app: casa-account
      version: v1
  template:
    metadata:
      labels:
        app: casa-account
        version: v1
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          image: gcr.io/vino9-276317/demo-bank/casa-account-v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
              protocol: TCP
          env:
            - name: GRPC_LISTEN_ADDR
              value: ":50051"
            - name: CASSANDRA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cassandra-secret
                  key: username
            - name: CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cassandra-secret
                  key: password
            - name: CASSANDRA_INSTANCE
              valueFrom:
                secretKeyRef:
                  name: cassandra-secret
                  key: instance
            - name: CASSANDRA_HOST
              valueFrom:
                secretKeyRef:
                  name: cassandra-secret
                  key: host
            - name: CASSANDRA_PORT
              valueFrom:
                secretKeyRef:
                  name: cassandra-secret
                  key: port
          resources:
            requests:
              cpu: 250m
              memory: 192Mi
            limits:
              cpu: 1000m
              memory: 384Mi
          volumeMounts:
            - name: astra-secure-bundle
              mountPath: "/astra"
              readOnly: true
      volumes:
      - name: astra-secure-bundle
        secret:
          secretName: cassandra-secret
          defaultMode: 0400
          items:
          - key: secure-connect-vino9.zip
            path: secure-connect-vino9.zip
---
apiVersion: v1
kind: Service
metadata:
  name: casa-account
spec:
  type: ClusterIP
  selector:
    app: casa-account
  ports:
    - name: grpc
      port: 50051
