resources:
  - ../../base

namespace: breeze

images:
  - name: gcr.io/vino9-276317/demo-bank/customer-v1
    newTag: latest
    newName: sloppycoder/bankdemo-customer-v1

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: customer-v1
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/0
        value: { "name": "TRACE_WITH_ZIPKIN", "value": "true" }
        # value: { "name": "TRACE_WITH_STACKDRIVER", "value": "true" }
