resources:
  - ../../base

namespace: breeze

images:
  - name: gcr.io/vino9-276317/demo-bank/customer-v1
    newTag: latest
    newName: sloppycoder/bankdemo-customer-v1

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: customer-v1
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/0
        value: { "name": "TRACE_WITH_ZIPKIN", "value": "true" }
      - op: add
        path: /spec/template/spec/containers/0/env/1
        value: { "name": "EXTERNAL_CUSTOMER_URL", "value": "http://ext-cust-svc:8080/customers" }
      - op: add
        path: /spec/template/spec/containers/0/env/2
        value: { "name": "LOG_LEVEL_ROOT", "value": "ERROR" }

    # patch: |-
    #   - op: add
    #     path: /spec/template/spec/containers/0/env/0
    #     value: { "name": "TRACE_WITH_STACKDRIVER", "value": "true" }
