#!/bin/bash

# exit when any command fails
set -e

KUSTOMIZE=$(which kustomize)

if [ -z "$KUSTOMIZE" ]; then
    echo "kustomize not found. please download from https://github.com/kubernetes-sigs/kustomize/releases"
    exit 1
fi

MODE=apply
if [ "$1" == "--delete" ]; then
    MODE=delete
fi

source ../common.sh
get_ingress_addr

case "$CTX" in

    "gke1")
        $KUSTOMIZE build envs/gke | kubectl $MODE -f -
        ;;

    "minikube")
        $KUSTOMIZE build envs/local | kubectl $MODE -f -
        ;;

    "")
        exit 1
        ;;
        
esac

echo service should be availabe at ${DEMOBANK_HOST}:${DEMOBANK_PORT}
