#!/bin/bash

# exit when any command fails
set -e

EVANS=$(which evans)

if [ -z "$EVANS" ]; then
    echo "evans not found. please download from https://github.com/ktr0731/evans/releases"
    exit 1
fi

source ../common.sh
get_ingress_addr

[ -z "$DEMOBANK_PORT" ] && exit 1

echo calling gRPC service at ${DEMOBANK_HOST}:${DEMOBANK_PORT}
echo '{ "login_name": "10001000" }' | $EVANS \
         --proto ../protos/demo_bank.proto   \
         --host $DEMOBANK_HOST \
         --port $DEMOBANK_PORT \
         cli \
         call \
         demobank.api.DashboardService.GetDashboard
