#!/bin/bash

# exit when any command fails
set -e

EVANS=$(which evans)

if [ -z "$EVANS" ]; then
    echo "evans not found. please download from https://github.com/ktr0731/evans/releases"
    exit 1
fi


DASHBOARD_HOST=$(kubectl get svc istio-ingressgateway -n istio-system -o jsonpath="{.status.loadBalancer.ingress[*].ip}")
echo calling gRPC service at ${DASHBOARD_HOST}:31400
echo '{ "login_name": "user001" }' | $EVANS --proto ../protos/demo_bank.proto   --host $DASHBOARD_HOST --port 31400 cli call demobank.api.DashboardService.GetDashboard
