#!/bin/bash

# exit when any command fails
set -e

EVANS=$(which evans)

if [ -z "$EVANS" ]; then
    echo "evans not found. please download from https://github.com/ktr0731/evans/releases"
    exit 1
fi

CTX=$(kubectl config current-context)
case "$CTX" in

    "gke1")
        DASHBOARD_HOST=$(kubectl get svc istio-ingressgateway -n istio-system -o jsonpath="{.status.loadBalancer.ingress[*].ip}")
        DASHBOARD_PORT=31400
        ;;

    "minikube")
        DASHBOARD_HOST=$(minikube ip)
        DASHBOARD_PORT=$(kubectl get svc istio-ingressgateway -n istio-system -o jsonpath="{.spec.ports[?(@.port=="443")].nodePort}")

        ;;

    "")
        echo No current kubectl context?...
        exit 1
        ;;

esac


echo calling gRPC service at ${DASHBOARD_HOST}:$DASHBOARD_PORT
echo '{ "login_name": "10001000" }' | $EVANS --proto ../protos/demo_bank.proto   --host $DASHBOARD_HOST --port $DASHBOARD_PORT cli call demobank.api.DashboardService.GetDashboard
