#!/bin/bash

# exit when any command fails
set -e

if [ -z "$USERS" ]; then
    USERS=1
fi

source ../common.sh
get_ingress_addr

[ -z "$DEMOBANK_PORT" ] && exit 1

echo generating load to ${DEMOBANK_HOST}:${DEMOBANK_PORT} with $USERS users

# activate python venv before running locust
if [ ! -f venv/bin/activate ]; then
    echo
    echo please create vitual environment venv and install app depenencies first. e.g.
    echo python -m venv venv
    echo source venv/bin/activate
    echo pip install -r requirements.txt
    echo

    exit 1
fi

source  venv/bin/activate

locust --host="${DEMOBANK_HOST}:${DEMOBANK_PORT}" --headless -u $USERS

