#!/bin/bash

# exit when any command fails
set -e

if [ -z "$USERS" ]; then
    USERS=1
fi

CTX=$(kubectl config current-context)
case "$CTX" in

    "gke1")
        DASHBOARD_HOST=$(kubectl get svc istio-ingressgateway -n istio-system -o jsonpath="{.status.loadBalancer.ingress[*].ip}")
        DASHBOARD_PORT=31400
        ;;

    "minikube")
        DASHBOARD_HOST=$(minikube ip)
        DASHBOARD_PORT=$(kubectl get svc istio-ingressgateway -n istio-system -o jsonpath="{.spec.ports[?(@.port=="443")].nodePort}")

        ;;

    "")
        echo No current kubectl context?...
        exit 1
        ;;

esac

echo generating load to ${DASHBOARD_HOST}:${DASHBOARD_PORT} with $USERS users

# activate python venv before running locust
if [ ! -f venv/bin/activate ]; then
    echo
    echo please create vitual environment venv and install app depenencies first. e.g.
    echo python -m venv venv
    echo source venv/bin/activate
    echo pip install -r requirements.txt
    echo

    exit 1
fi

source  venv/bin/activate

locust --host="${DASHBOARD_HOST}:${DASHBOARD_PORT}" --headless -u $USERS

