# we create these in istio-system namespace to mimick regular istio installation

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-gcp
  namespace: istio-system
  labels:
    app: zipkin-gcp
spec:
  selector:
    matchLabels:
      app: zipkin-gcp
  template:
    metadata:
      labels:
        app: zipkin-gcp
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: zipkin-gcp
          image: openzipkin/zipkin-gcp:0.16
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9410
              protocol: TCP
            - containerPort: 9411
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 2000m
              memory: 1024Mi
          env:
            # this is required for sending traces directly to stackdriver
            - name: STORAGE_TYPE
              value: "stackdriver"
            # uncomment the following to debug permission issues
            # - name: STACKDRIVER_HTTP_LOGGING
            #   value: "HEADERS"

---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: istio-system
  labels:
    app: zipkin-gcp
spec:
  type: ClusterIP
  selector:
    app: zipkin-gcp
  ports:
    - name: http
      port: 9411
      targetPort: 9411
